### ISSUE TITLE
Estimated time for code and data release?

### ISSUE THREAD

**Issue by makeme-zgz** [nv-tlabs/ASE#1]

**Comment by xbpeng** [comment]
we are aiming for a code release in july

**Comment by Jesse-zjx** [comment]
@xbpeng  thanks for releasing this great work. Can't wait to try it out. Would be appreciate if the code can be released soon.

**Comment by xbpeng** [comment]
We need to go through an internal review process before the code can be released, we are working on that now.

**Comment by craftsliu** [comment]
looking forward to code released

**Comment by makeme-zgz** [comment]
Thanks for the code releasing!
