### ISSUE TITLE
Error for key= global_root_yaw_rotation 

### ISSUE THREAD

**Issue by craftsliu** [nv-tlabs/ASE#12]
Loading 1/87 motion files: ase/data/motions/reallusion_sword_shield/RL_Avatar_Atk_2xCombo01_Motion.npy

Error for key= global_root_yaw_rotation 
Error for key= global_translation_xy
Error for key= global_translation_xz
Error for key= local_translation_to_root
Error for key= root_translation_xy
Total added 17

What does this error mean?what impact will it have?

**Comment by xbpeng** [comment]
you can ignore those errors, they are expected.
