### ISSUE TITLE
What exactly is amp_humanoid_task.yaml for?

### ISSUE THREAD

**Issue by ameliacode** [nv-tlabs/ASE#16]
Hi I have been playing around with your code.
I've noticed that there is an unused yaml for training, amp_humanoid_task.yaml,
and I assume that maybe, this file was for amp task training. I guess..?

Is it possible to train task out of this file instead of invoking ase_humanoid_hrl.yaml inside hrl_humanoid.yaml?  
or should I just simply call amp_humanoid_task.yaml for task training?

**Comment by xbpeng** [comment]
Hi Amelia,

That's right, amp_humanoid_task.yaml is for training a policy using AMP to simultaneously imitate motion data and satisfy high level task objectives. You can replace hrl_humanoid.yaml with amp_humanoid_task.yaml to train an AMP model from scratch for a particular task. Note you do not need to replace ase_humanoid_hrl.yaml inside hrl_humanoid.yaml, instead replace hrl_humanoid.yaml in the command with amp_humanoid_task.yaml.
