### ISSUE TITLE
Full motion dataset and Retargeting.

### ISSUE THREAD

**Issue by Frank-Dz** [nv-tlabs/ASE#19]
Hi, Jason! Thanks for your great work!
I found there are 187 motion clips used for the low-level controller. > "The low-level policy is trained using a custom motion dataset of 187 motion clips, provided by Reallusion [Reallusion 2022].
However, from Reallusion, there are only 87 clips. May I know where are other 100 clips?
![image](https://user-images.githubusercontent.com/55009565/202710481-e45f8621-958a-4f04-b340-25ccc719a824.png)

Another question would be, will you release the retargeting script for the motion files from Reallusion? Thank you so much!

**Comment by xbpeng** [comment]
Hi Frank, the other motion clips of regular locomotion skills. We dont have the reallusion retargeting script ready for release at the moment. But you can follow the setup for the CMU and SFU configs. It should be very similar.
