### ISSUE TITLE
Possible to provide training histories?

### ISSUE THREAD

**Issue by dtch1997** [nv-tlabs/ASE#29]
Would it be possible to release training logs (i.e. Tensorboard) for the pre-trained low-level controller? `ase/data/models/ase_llc_reallusion_sword_shield.pth`

This would help us understand things like how long the training run takes, typical learning curve, GPU utilization etc.

**Comment by dtch1997** [comment]
My own training run has finished after 2 days and here is the training history if anyone else is interested. https://wandb.ai/dtch1997/QuadrupedASE/reports/HumanoidAMPGetup--VmlldzozNTgwNTUz?accessToken=pp02sojqaovrz79u44oposop6o7vel333gayha1o83nesd4a33ktf2qxkmk6nfl5

And here is associated checkpoint: https://drive.google.com/file/d/1bXhgahdG-ZirQC0Q-RMr8X5nBK1VTLbR/view?usp=share_link

From brief visual inspection, performance seemed similar to the checkpoint provided with the repo.

**Comment by xbpeng** [comment]
thanks for sharing those!
