### ISSUE TITLE
Angle representation for 3 dof joints

### ISSUE THREAD

**Issue by braunjon** [nv-tlabs/ASE#30]
Hi,

I have a short question about the angle representation, as I must miss something obvious.

In the [amp_humanoid_sword_shield.xml](https://github.com/nv-tlabs/ASE/blob/main/ase/data/assets/mjcf/amp_humanoid_sword_shield.xml) file the 3 dof joints are defined with three hinge joints. However, the motion lib converts the joint angles to rotation vectors / exponential map:
https://github.com/nv-tlabs/ASE/blob/de18a567649964d5f12b2bc31f44489d3ef26229/ase/utils/motion_lib.py#L336-L339

Why should it not be Euler angles? (Does this mean the trained llc output as action (scaled) rotation vectors for 3 dof joints?)

Thanks!

**Comment by xbpeng** [comment]
IsaacGym internally converts sequences of 3 hinge joints into a single 3dof spherical joint. The rotation of spherical joints are represented using exp maps, you should not use euler angles for those.

**Comment by braunjon** [comment]
Thanks!
