### ISSUE TITLE
errors when trying to install autodesk's FBX sdk and python bindings on Ubuntu, is there a trick to this?

### ISSUE THREAD

**Issue by Robokan** [nv-tlabs/ASE#37]
What is the trick to installing this on Ubuntu 20.04?

I have followed all the instructions and even compiling Sip from source (4.19.3) but still can't get this working. I want to use the FBX importer to bring in some animations for ASE.

after installing the sdk and the python bindings:

python PythonBindings.py Python3_x86 buildsip

......

In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:194,
                 from /usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h:34,
                 from /home/bizon/anaconda3/envs/rlase/include/python3.8/Python.h:11,
                 from ./sip.h:32,
                 from sipAPIfbx.h:41,
                 from sipfbxFbxBindingTable.cpp:38:
/usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

any ideas? Has anyone else gotten FBX installed and working?

**Comment by Robokan** [comment]
I managed to finally install this. Looks to be quite a few hurdles at this point. Such as missing Libraries and link order problems when  it creates the make file.

The main problem is it links the fbx library statically after dynamically linking with libxml2 but references libxml2. So the link order must be changed to link the fbx library before libxml2 to work.

**Comment by hhebb** [comment]
> I managed to finally install this. Looks to be quite a few hurdles at this point. Such as missing Libraries and link order problems when it creates the make file.
> 
> The main problem is it links the fbx library statically after dynamically linking with libxml2 but references libxml2. So the link order must be changed to link the fbx library before libxml2 to work.

it helped thanks.
