### ISSUE TITLE
Issue while running ASE using isaac gym 1.0prview4

### ISSUE THREAD

**Issue by Bearil** [nv-tlabs/ASE#41]
Is it a way to run ASE using isaac gym 1.0prview4? Actually, I have an error while running:
`python ase/run.py --task HumanoidAMPGetup --cfg_env ase/data/cfg/humanoid_ase_sword_shield_getup.yaml --cfg_train ase/data/cfg/train/rlg/ase_humanoid.yaml --motion_file ase/data/motions/reallusion_sword_shield/dataset_reallusion_sword_shield.yaml --headless`

It is an incompatibility between the torch requirements of ASE and the latest Isaac Gym version (1.0preview4). I didn't find any options to download the earliest versions of Isaac Gym, the links are unavailable.

Thanks for advice

**Comment by Bearil** [comment]
I am successfully running the training process using the latest version of Isaac gym (1.0prview4) process after updating GPU drivers and installing the C++ compiler

**Comment by DannyChen1994** [comment]
Can you tell us more about what you did? I can also only download to ISAAC Gym Preview 4. Unable to run the ASE sample program.
