### ISSUE TITLE
Sudden drop of task rewards

### ISSUE THREAD

**Issue by xizaoqu** [nv-tlabs/ASE#44]
![image](https://github.com/nv-tlabs/ASE/assets/45515569/c0f1bb0e-e434-45d0-8319-6f92b9f17ba5)

Sometimes task rewards will suddenly drop to very low and discriminator rewards will go high. Is it normal?

**Comment by xbpeng** [comment]
This is not normal. It could be a sign that the hyperparameters need some tuning, or there is an issue with the setup somewhere. What are the weights for the task reward and disc reward?
