### ISSUE TITLE
Error when training imitation use amp_humanoid_task.yaml

### ISSUE THREAD

**Issue by interestingzhuo** [nv-tlabs/ASE#47]
I have trained the model to tracking a motion sequence with command 
```
python ase/run.py --task HumanoidImitation  --cfg_env ase/data/cfg/humanoid_imitation.yaml --cfg_train ase/data/cfg/train/rlg/amp_humanoid_task.yaml --motion_file xxx --checkpoint output/Humanoid_20-14-34-09/nn/Humanoid.pth
```
and test with 
```
python ase/run.py --test --task HumanoidImitation --num_envs 1 --cfg_env ase/data/cfg/humanoid_imitation.yaml --cfg_train ase/data/cfg/train/rlg/amp_humanoid_task.yaml --motion_file xxx--checkpoint xxx
```
 The humanoid_imitation.py is changed to track a reference motion.
But the robot  will  jump high at the begining when test.

**Comment by interestingzhuo** [comment]
https://github.com/nv-tlabs/ASE/assets/43921151/593e08cf-e957-4b77-afb5-a1dea1234a8d

**Comment by interestingzhuo** [comment]
https://github.com/nv-tlabs/ASE/assets/43921151/a746bad8-ae6a-4fe5-b5c7-891c8cbe643c

**Comment by xbpeng** [comment]
Have you tried moving the red sphere to a different location that doesn't intersect with the character? It looks like the jumping is due to an intersection between the sphere and the character.

**Comment by interestingzhuo** [comment]
https://github.com/nv-tlabs/ASE/assets/43921151/b1068faa-efe8-4e9c-8039-bb22b92d2c6d

I moved  the red sphere away from the character but the jumping still exists. I also use the model to imitate some more difficult motion, it works. The imitation of easy motion often fails.

https://github.com/nv-tlabs/ASE/assets/43921151/db63b170-545a-4836-951f-63f3ad42041e

**Comment by xbpeng** [comment]
mmm that is weird. It's a bit hard to tell in the video, but does the jump happen right at the start of an episode? Does the jump still happen if you just add an offset to the height of the root so the character is off the ground?

**Comment by interestingzhuo** [comment]
> mmm that is weird. It's a bit hard to tell in the video, but does the jump happen right at the start of an episode? Does the jump still happen if you just add an offset to the height of the root so the character is off the ground?
The jump only  happens right at the start of an episode?

**Comment by xbpeng** [comment]
this looks like an issue with the character having a little bit of ground penetration. Does add an offset to initial height help?

**Comment by interestingzhuo** [comment]
> this looks like an issue with the character having a little bit of ground penetration. Does add an offset to initial height help?

Thx! It works!
