### ISSUE TITLE
About the DOF conversion of character motions.

### ISSUE THREAD

**Issue by 3-body** [nv-tlabs/ASE#54]
Hi, Jason
I load Reallusion's fbx motion and map relevant joints to ATLAS model that all joints is 1D.
But most poses seem bad exclude knees, elbows, and z-axes of hips after retargeted to npy motion. 
Some Q:
1. Does this mean that need to convert all other abnormal joints from 3D to 1D?
2. How to get the THETAs(both end joints, x-axis of ankle, z-axis of hip)?
3. So expensive Reallusion's motions, so less the cmu's DOF, any other options? Wandering.
@xbpeng

https://github.com/nv-tlabs/ASE/assets/8104370/fbf28089-9b02-44de-af9b-7fd64af69ff1

"CC_Base_Hip": "pelvis",
"CC_Base_L_Thigh": "l_uglut",
"CC_Base_L_ThighTwist02": "l_lglut",
"CC_Base_L_ThighTwist01": "l_uleg",
"CC_Base_L_Calf": "l_lleg",
"CC_Base_L_CalfTwist02": "l_ankle",
"CC_Base_L_Foot": "l_foot",
"CC_Base_R_Thigh": "r_uglut",
"CC_Base_R_ThighTwist02": "r_lglut",
"CC_Base_R_ThighTwist01": "r_uleg",
"CC_Base_R_Calf": "r_lleg",
"CC_Base_R_CalfTwist02": "r_ankle",
"CC_Base_R_Foot": "r_foot",
"CC_Base_Waist": "ltorso",
"CC_Base_Spine01": "mtorso",
"CC_Base_Spine02": "utorso",
"CC_Base_L_Clavicle": "l_shoulder",
"CC_Base_L_Upperarm": "l_uarm",
"CC_Base_L_ElbowShareBone": "l_ufarm",
"CC_Base_L_ForearmTwist01": "l_dfarm",
"CC_Base_L_ForearmTwist02": "l_hb_hand",
"CC_Base_R_Clavicle": "r_shoulder",
"CC_Base_R_Upperarm": "r_uarm",
"CC_Base_R_ElbowShareBone": "r_ufarm",
"CC_Base_R_ForearmTwist01": "r_dfarm",
"CC_Base_R_ForearmTwist02": "r_hb_hand"

https://github.com/nv-tlabs/ASE/assets/8104370/e4d2f706-3d43-4140-95a5-27f0a2e73199

**Comment by xbpeng** [comment]
yes, you will need to first convert the 3d rotations in the mocap data to 1d rotations for the Atlast model. You can't directly use the exponential maps as 1D rotations. It can be pretty tricky to do this correctly tho. The best way is probably to use inverse kinematics to retarget the motion in this case due to the drastic differences in morphology.

**Comment by 3-body** [comment]
> yes, you will need to first convert the 3d rotations in the mocap data to 1d rotations for the Atlast model. You can't directly use the exponential maps as 1D rotations. It can be pretty tricky to do this correctly tho. The best way is probably to use inverse kinematics to retarget the motion in this case due to the drastic differences in morphology.

Thanks for your reply!
I‘m trying to retarget it with IK method.
