### ISSUE TITLE
Error when import FBX

### ISSUE THREAD

**Issue by jianrenw** [nv-tlabs/ASE#55]
I am encountering an issue while trying to install and use the FBX Python bindings from Autodesk's official link (https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-2-1) on my Anaconda environment with Python 3.8 on Ubuntu 20.04. The installation seems to be successful, but when I attempt to import the FBX module using import fbx, I receive the following error:

"ImportError: fbxpy/build/Distrib/site-packages/fbx/fbx.so: undefined symbol: xmlFree"

I am seeking assistance in resolving this issue. Any help or guidance would be greatly appreciated. Thank you!

**Comment by hhebb** [comment]
did you solved problem??
if so, can you figure out how to solve??
thanks
