### ISSUE TITLE
How to tune hyper parameters for GPU's with more memory?

### ISSUE THREAD

**Issue by Robokan** [nv-tlabs/ASE#56]
I have a dedicated RTX 4090 with 24 g of memory. When training ASE it only uses only half of the available memory. What changes to the hyper parameters can I make to use more of the GPU?

**Comment by mjdxyr** [comment]
Maybe you can look https://github.com/NVlabs/CALM/issues/4 for some help.

**Comment by Robokan** [comment]
Yes, I have been running CALM as well. I read that post a while back and used it to turn everything down. Hoping to turn everything up on ASE as it's less resource intensive.

**Comment by xbpeng** [comment]
You can increase memory usage by increasing the number of environments `numEnvs` in https://github.com/nv-tlabs/ASE/blob/main/ase/data/cfg/humanoid_ase.yaml,
 increase the number of samples collected per iteration `horizon_length`, and the minibatch size used for gradient calculation `minibatch_size` and `amp_minibatch_size` in https://github.com/nv-tlabs/ASE/blob/main/ase/data/cfg/train/rlg/ase_humanoid.yaml.

**Comment by Robokan** [comment]
Great thanks! Exactly what I was looking for.
