### ISSUE TITLE
[fbx_sdk install manual] if you stucked in install fbx_sdk for import fbx or other files. check this

### ISSUE THREAD

**Issue by hhebb** [nv-tlabs/ASE#61]
finally i installed fbx sdk in my machine.
it was not easy, so those who suffering to install fbx_sdk, i hope this helps.
i wrote that manual with many googling and trial.

```
environment

* Ubuntu 20.04 LTS
* python 3.8.10
```

1. download and install fbx sdk
    - fbx sdk
        - version
            - 202032
        - tar file download path
            - `./<YOUR_FBXSDK_PATH>/`
        - instruction
            - `cd <YOUR_FBXSDK_PATH>`
            - `tar zxvf fbx202032_fbxsdk_linux.tar.gz`
            - `./fbx202032_fbxsdk_linux.tar.gz`
            - `export FBXSDK_ROOT=<YOUR_FBXSDK_PATH>`
        - you should check env param
    - fbx python binding
        - version
            - 202032
        - tar file download path
            - `./YOUR_FBX_PYTHON_BINDING_PATH/`
        - instruction
            - `cd <YOUR_FBX_PYTHON_BINDING_PATH>`
            - `tar zxvf fbx202032_fbxpythonbindings_linux.tar.gz`
            - `./fbx202032_fbxpythonbindings_linux.tar.gz`
    - reference
        - [[autodesk FBX SDK 202032](https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-3.2)](https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-3.2)
        - no need **fbx python sdk**
2. sip - build tool
    - version
        - 4.19.3
    - file download path
        - `./<YOUR_SIP_PATH>/`
    - install
        - `cd <YOUR_SIP_PATH>`
        - `python configure.py`
        - `make`
        - `make install`
        - `export SIP_ROOT=<YOUR_SIP_PATH>`
    - you should check env param
    - reference
        - [[sip==4.19.3 archive file download](https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.3/)](https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.3/)
        - [[how to install sip](https://docs.huihoo.com/pyqt/sip4/installation.html)](https://docs.huihoo.com/pyqt/sip4/installation.html)
3. sdk build
    - `cd <YOUR_FBX_PYTHON_BINDING_PATH>`
    - `python PythonBindings.py Python3_x64 buildsip`
    - when get problem with lxml
        - `sudo apt insatll libxml2-dev`
        - `python PythonBindings.py Python3_x64 buildsip`
4. modify make file and re-install
    - there is possibility of error when import fbx after first build.
        - `fbx undefined symbol: xmlFree`
        - that is error about link order related with libxml2.so's
        - you should modify the make file
        - [[make file modify](https://forums.autodesk.com/t5/fbx-forum/fbx-python-bindings-fails-on-ubuntu-because-of-undefined-symbol/td-p/9538320)](https://forums.autodesk.com/t5/fbx-forum/fbx-python-bindings-fails-on-ubuntu-because-of-undefined-symbol/td-p/9538320)
    - `cd <YOUR_FBX_PYTHON_BINDING_PATH>/build/Python38_x64`
    - `make clean`
    - open make file and modify
        
        ```bash
        from

        LIBS = -L/workspace/CALM/fbxsdk/lib/gcc/x64/release -lz -lxml2 /workspace/CALM/fbxsdk/lib/gcc/x64/release/libfbxsdk.a
        
        to
        
        LIBS = -L/workspace/CALM/fbxsdk/lib/gcc/x64/release /workspace/CALM/fbxsdk/lib/gcc/x64/release/libfbxsdk.a -lz -lxml2
        
        ```
        
    - `make install`
    - files are created in `<YOUR_FBX_PYTHON_BINDING_PATH/build/Distrib/site-packages/fbx>` after installing
        - `fbx.so`
        - `FbxCommon.py`
        - `fbxsip.so`
    - and file is copied to `<YOUR_PIP_PATH>/site-packages`
        - `fbx.so`
5. add sys path to your .py file
    - the package paths are not added to python sys.path, you should add path manually.
    - maybe i should move`<YOUR_FBX_PYTHON_BINDING_PATH/build/Distrib/site-packages/fbx>` to my python site-package. and maybe don't need this step.
        
        ```python
        import sys
        sys.path.append('<YOUR_FBX_PYTHON_BINDING_PATH>/build/Distrib/site-packages/fbx/')
        ...
        ```
        
    - now you can successfully import fbx, FbxCommon packages.
7. other reference
    - [[env param setting](https://github.com/Shiiho11/FBX-Python-SDK-for-Python3.x/blob/master/BuildGuide_EN.md)](https://github.com/Shiiho11/FBX-Python-SDK-for-Python3.x/blob/master/BuildGuide_EN.md)

**Comment by ziyanx02** [comment]
I get `/usr/bin/ld: cannot find -lz` as well as `/usr/bin/ld: cannot find -lxml2` while building pythonbindings. It's caused by the missing of both zlib and libxml2 (not sure if it's common to miss libz). The problem can be solved by `sudo apt install zlib1g-dev libxml2-dev`.
It took me some time to find out which package `-lz` stands for, so I comment here for those who may stuck on the same problem as me.

**Comment by xiaohu-art** [comment]
# Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbxsip'

**Comment by Hellod035** [comment]
> # Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbxsip'

I also encountered the same problem in Ubuntu 22.04. Is there any solution?

**Comment by shijiyuanaa** [comment]
> > # Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbxsip'
> 
> I also encountered the same problem in Ubuntu 22.04. Is there any solution?

after modifying the Makefile, run `sudo make` before make install

**Comment by Gloriabhsfer** [comment]
> > > # Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbxsip'
> > 
> > 
> > I also encountered the same problem in Ubuntu 22.04. Is there any solution?
> 
> after modifying the Makefile, run `sudo make` before make install

I encounter the same problem and already try sudo make before make install but the fbxsip still not find. Any ideas???

**Comment by lq2520362** [comment]
Thanks for the solution. I still encountered many problems locally, such as "No module named 'fbxsip'"
But I found another simple way that worked very well for me, which is to use python3.7 when processing FBX data.
Just download the **fbx python sdk** and put it in the site-packages directory.
like:
      ~/miniconda/envs/xxx/lib/python3.7/site-packages/sip.so
      ~/miniconda/envs/xxx/lib/python3.7/site-packages/FbxCommon.py
      ~/miniconda/envs/xxx/lib/python3.7/site-packages/fbxsip.so
After you finish processing the fbx data, you can still switch back to the python environment you used before.

[autodesk FBX SDK 202032](https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-3.2)
