### ISSUE TITLE
Unable to achieve good results on Humanoid Reach/Location/Strike tasks

### ISSUE THREAD

**Issue by floodsung** [nv-tlabs/ASE#9]
Hi Jason,
I am trying to train the tasks but only Humanoid Heading works, others failed with pretty low rewards. I train the task following your script like this:

`python ase/run.py --task HumanoidReach --cfg_env ase/data/cfg/humanoid_sword_shield_reach.yaml --cfg_train ase/data/cfg/train/rlg/hrl_humanoid.yaml --motion_file ase/data/motions/reallusion_sword_shield/RL_Avatar_Idle_Ready_Motion.npy --llc_checkpoint ase/data/models/ase_llc_reallusion_sword_shield.pth --headless
`
Is there anything wrong in the config? And can you share the trained model?
Thx

**Comment by xbpeng** [comment]
Yea, seems like the tasks are not working as well as I expected. There might be an issue with the retrained ASE model. Looking into it now.

**Comment by xbpeng** [comment]
The task training issues should be fixed now. I've also uploaded new pre-trained models for the low-level controllers and high-level controllers.

**Comment by floodsung** [comment]
Thank you. I have tested and it works!

**Comment by xbpeng** [comment]
It wasn't so much an issue with the pre-trained model. I just had to tweak the reward functions for the downstream tasks a bit. Had to shape the reward a bit to give the character more incentive to move towards the target.
